name: Build and Push Docker Image

on:  # Add a colon after "on" keyword
  push:
    branches: [ alltalkbeta ]  # Change to your desired branch(es)

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Important: Grant write permission to packages

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push the image
        run: |
          ./docker-build.sh --tag ${{ github.sha }}
          docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }}
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest # github.repository_name is lowercase
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:${{ github.sha }}


      - name: Clean up Docker cache
        uses: actions/cache@v3
        with:
          path: ~/.docker/buildx/cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-