name: Build and Push Docker Images

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: "nvidia.Dockerfile"
            platforms: "linux/amd64"
            tag_name: "cuda"
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata
        id: meta
        run: |
          echo "REPO_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-')" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ env.REPO_LOWER }}:${{ matrix.tag_name }}-${{ env.BRANCH_NAME }}
            ${{ github.ref == 'refs/heads/main' && format('ghcr.io/{0}:{1}-latest', env.REPO_LOWER, matrix.tag_name) || '' }}
            ${{ github.ref == 'refs/heads/main' && format('ghcr.io/{0}:{1}', env.REPO_LOWER, matrix.tag_name) || '' }}
